# Generated by Django 4.1.3 on 2023-02-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_items', models.CharField(max_length=255)),
                ('description_items', models.CharField(max_length=255)),
            ],
        ),
    ]
