# Generated by Django 4.1.3 on 2023-03-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_items_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='author_id_item',
            field=models.IntegerField(null=True),
        ),
    ]
