# Generated by Django 4.1.3 on 2023-03-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_items_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='category',
            new_name='category_items',
        ),
    ]
