# Generated by Django 4.1.3 on 2023-03-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_rename_category_items_category_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items_Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_user_review', models.CharField(max_length=255)),
                ('id_user_review', models.IntegerField(null=True)),
                ('date_reviews', models.IntegerField(null=True)),
                ('text_review', models.CharField(max_length=255)),
                ('advantages_item', models.CharField(max_length=255)),
                ('disadvantages_item', models.CharField(max_length=255)),
            ],
        ),
    ]
