# Generated by Django 4.1.3 on 2023-03-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_items_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_reviews',
            name='date_reviews',
            field=models.DateField(null=True),
        ),
    ]
