# Generated by Django 4.1.3 on 2023-03-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_items_reviews_date_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_reviews',
            name='id_item_comment',
            field=models.IntegerField(null=True),
        ),
    ]
