# Generated by Django 4.1.3 on 2023-03-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_rename_id_item_comment_items_reviews_id_item_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_reviews',
            name='difsdfsdsadvantages_item',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
