# Generated by Django 4.1.3 on 2023-03-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_items_reviews_difsdfsdsadvantages_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items_reviews',
            name='difsdfsdsadvantages_item',
        ),
    ]
