# Generated by Django 4.1.3 on 2023-03-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_remove_items_reviews_difsdfsdsadvantages_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items_Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_user_Questions', models.CharField(max_length=255)),
                ('id_user_Questions', models.IntegerField(null=True)),
                ('id_item_Questions', models.IntegerField(null=True)),
                ('date_Questions', models.DateField(null=True)),
                ('text_Questions', models.CharField(max_length=255)),
            ],
        ),
    ]
