# Generated by Django 4.1.3 on 2023-03-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_items_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_questions',
            name='count_useful_Questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='items_reviews',
            name='count_useful_review',
            field=models.IntegerField(default=0),
        ),
    ]
