# Generated by Django 4.1.3 on 2023-02-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
