# Generated by Django 4.1.3 on 2023-02-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='password_user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
