# Generated by Django 4.1.3 on 2023-03-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_users', '0002_registration_password_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password_user',
            field=models.CharField(max_length=20),
        ),
    ]
